## Clash Config
## Schema: https://raw.githubusercontent.com/MetaCubeX/mihomo/refs/heads/Meta/docs/config.yaml

## Set Up Global Variables
##   Test node speed in every 5 minutes
##   Update subscription in every 24 hours
.VARIABLES:
  - &SPEEDTEST_IV 300     # 5 mins
  - &UPDATE_IV 86400      # 24 hours
  - &SPEED_TOLERANCE 30   # Switch if faster than 30 ms


## Subscription Info
proxy-providers:
  provider_1:             # Custom Name for Nodes Provider
    type: http            # Fetch nodes from http
    url: "your-subscription-link"
    proxy: DIRECT         # Fetch nodes via DIRECT traffic
    interval: *UPDATE_IV  # Auto-update interval
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204 # Connection test site
      interval: *UPDATE_IV
  # provider_2:             # You can add multiple prodivers below


## Global Proxy Settings
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
unified-delay: false
tcp-concurrent: true
mode: rule
log-level: info
ipv6: false
profile:
  store-selected: true   # Memorize the node selected last time
  store-fake-ip: true    # Cache fake-ip mappings to local for faster access


## DNS Settings (DO NOT MODIFY FOR UNKNOWN REASONS)
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
  nameserver:
    - 223.5.5.5       # Aliyun
    - 119.29.29.29    # Tencent


## Group Nodes Fetched from Providers
proxy-groups:
  - {name: ALL, type: select, include-all: true}
  - {name: HongKong, include-all: true, type: fallback, interval: *SPEEDTEST_IV, filter: "(?i)香港|hong\\s?kong|hk"}
  - {name: Macau, include-all: true, type: fallback, interval: *SPEEDTEST_IV, filter: "(?i)澳门|macau|macao|mo"}
  - {name: Taiwan, include-all: true, type: fallback, interval: *SPEEDTEST_IV, filter: "(?i)台湾|taiwan|tw"}
  - {name: Japan, include-all: true, type: fallback, interval: *SPEEDTEST_IV, filter: "(?i)日本|东京|tokyo|japan|jp"}
  - {name: Korea, include-all: true, type: fallback, interval: *SPEEDTEST_IV, filter: "(?i)韩国|南韩|首尔|seoul|korea|south\\s?korea|kr"}
  - {name: Singapore, include-all: true, type: fallback, interval: *SPEEDTEST_IV, filter: "(?i)新加坡|狮城|singapore|sg"}
  - {name: UnitedStates, include-all: true, type: fallback, interval: *SPEEDTEST_IV, filter: "(?i)美国|united\\s?states|usa|us"}
  - {name: UnitedKingdom, include-all: true, type: fallback, interval: *SPEEDTEST_IV, filter: "(?i)英国|united\\s?kingdom|uk"}
  - {name: Canada, include-all: true, type: fallback, interval: *SPEEDTEST_IV, filter: "(?i)加拿大|canada|ca"}
  - {name: Others, type: select, include-all: true, exclude-filter: "(?i)香港|hong\\s?kong|hk|澳门|macau|macao|mo|台湾|taiwan|tw|新加坡|狮城|singapore|sg|美国|united\\s?states|usa|us|日本|东京|tokyo|japan|jp|韩国|南韩|首尔|seoul|korea|south\\s?korea|kr|英国|united\\s?kingdom|uk|加拿大|canada|ca"}


## Subcribe Rule Sets from providers
rule-anchor:
  .DOMAIN_MRS: &DOMAIN_MRS {type: http, interval: *UPDATE_IV, behavior: domain, format: mrs, proxy: HongKong}   # Fetch rule list from provider with proxy traffic
  .DOMAIN_LST: &DOMAIN_LST {type: http, interval: *UPDATE_IV, behavior: domain, format: text, proxy: HongKong}
  .IP_MRS: &IP_MRS {type: http, interval: *UPDATE_IV, behavior: ipcidr, format: mrs, proxy: HongKong}

rule-providers:
  ai-domains: { <<: *DOMAIN_LST, url: "https://raw.githubusercontent.com/yy1iang/oh-my-clash/refs/heads/main/rulesets/ai.list"}
  bio-domains: { <<: *DOMAIN_LST, url: "https://raw.githubusercontent.com/yy1iang/oh-my-clash/refs/heads/main/rulesets/biology.list"}
  github-domains: { <<: *DOMAIN_MRS, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/github.mrs"}
  reddit-domains: { <<: *DOMAIN_MRS, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/reddit.mrs"}
  synology-domains: { <<: *DOMAIN_MRS, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/synology.mrs"}
  netflix-domains: { <<: *DOMAIN_MRS, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/netflix.mrs"}
  meta-domains: { <<: *DOMAIN_MRS, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/meta.mrs"}               # Facebook, Instegram, Whatsapp
  x-domains: { <<: *DOMAIN_MRS, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/x.mrs"}                     # Twitter, Grok
  google-domains: { <<: *DOMAIN_MRS, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/google.mrs"}
  apple-domains: { <<: *DOMAIN_MRS, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/apple.mrs"}
  microsoft-domains: { <<: *DOMAIN_MRS, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/microsoft.mrs"}
  CN-domains: { <<: *DOMAIN_MRS, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/cn.mrs"}
  CN-IPs: { <<: *IP_MRS, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/cn.mrs"}


## Assign Proxy Group to Rule Set
rules:
  - SRC-IP-CIDR,192.168.2.136/32,DIRECT    # webcam
  - SRC-IP-CIDR,192.168.2.171/32,DIRECT    # webcam
  - RULE-SET,ai-domains,UnitedStates
  - RULE-SET,github-domains,UnitedStates
  - RULE-SET,reddit-domains,UnitedStates
  - RULE-SET,bio-domains,HongKong
  - RULE-SET,netflix-domains,HongKong
  - RULE-SET,meta-domains,HongKong
  - RULE-SET,x-domains,HongKong
  - RULE-SET,google-domains,HongKong
  - RULE-SET,microsoft-domains,HongKong
  - RULE-SET,apple-domains,DIRECT
  - RULE-SET,synology-domains,DIRECT
  - RULE-SET,CN-domains,DIRECT
  - RULE-SET,CN-IPs,DIRECT
  - MATCH,HongKong